apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: awx-clus-1
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/eingram23/kubernetes.git
    targetRevision: main
    path: argocd/environments/prod/clus-1/overlays/awx
  destination:
    namespace: awx
    server: https://rancher.local.lan/k8s/clusters/c-m-twrrzfwf
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true