apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: es-cert-manager-vault-secret
  namespace: cert-manager
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: cert-manager-vault-secret
  data:
  - secretKey: secretId
    remoteRef:
      key: approle/cert-manager
      property: secret_id
