apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: awx-tls
  namespace: awx
spec:
  secretName: awx-tls
  issuerRef:
    kind: ClusterIssuer
    name: vault-cluster-issuer
  commonName: awx.local.lan
  dnsNames:
  - awx.local.lan
  duration: 8760h
  renewBefore: 4380h
