project: default
source:
  - repoURL: https://github.com/influxdata/helm-charts.git
    path: charts/influxdb2
    targetRevision: HEAD
  - repoURL: 'https://github.com/eingram23/kubernetes.git'
    path: argoapps/influxdb/manifests
    targetRevision: HEAD
destination:
  server: https://kubernetes.default.svc
  namespace: influxdb
syncPolicy:
  syncOptions:
    - CreateNamespace=true