apiVersion: v1
kind: Pod
metadata:
  name: awx-postgres-13-0
  namespace: awx
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: k3s2
            operator: In
            values:
            - kubernetes.io/hostname
  containers:
  - name: postgres
    image: postgres:13
    imagePullPolicy: IfNotPresent
