apiVersion: v1
kind: Pod
metadata:
  name: splunk-stdln-standalone-0
  namespace: splunk
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: k3s3
            operator: In
            values:
            - kubernetes.io/hostname
  containers:
  - name: splunk
    image: docker.io/splunk/splunk:9.1.2
    imagePullPolicy: IfNotPresent
