apiVersion: run.tanzu.vmware.com/v1alpha2
kind: TanzuKubernetesCluster
metadata:
  name: tkgs-v2-cluster-xsmall
  namespace: test
spec:
  topology:
    controlPlane:
      replicas: 1
      vmClass: best-effort-xsmall
      storageClass: vsan-default-storage-policy
      tkr:  
        reference:
          name: v1.21.2---vmware.1-tkg.1.ee25d55
    nodePools:
    - name: worker-nodepool-a1
      replicas: 1
      vmClass: best-effort-xsmall
      storageClass: vsan-default-storage-policy
      tkr:  
        reference:
          name: v1.21.2---vmware.1-tkg.1.ee25d55