---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vault
  annotations:
    kubernetes.io/ingress.class: "traefik"
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: vault
            port:
              number: 8200

---
apiVersion: v1
kind: Service
metadata:
  name: vault
spec:
  ports:
    - port: 8200
      protocol: TCP
  selector:
    app:  vault

---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    io.kubernetes.cri-o.ContainerType/vault-dev-server: container
    io.kubernetes.cri-o.SandboxID/vault-dev-server: vault
    io.kubernetes.cri-o.TTY/vault-dev-server: "false"
    io.podman.annotations.autoremove/vault-dev-server: "FALSE"
    io.podman.annotations.init/vault-dev-server: "FALSE"
    io.podman.annotations.privileged/vault-dev-server: "FALSE"
    io.podman.annotations.publish-all/vault-dev-server: "FALSE"
  creationTimestamp: "2022-09-11T23:20:37Z"
  labels:
    app: vault
  name: vault
  namespace: default
spec:
  selector:
    matchLabels:
      app: vault
  replicas: 3
  template:
    metadata:
      labels:
        app: vault
    spec:
      containers:
      - args:
        - server
        - -dev
        env:
        - name: VAULT_DEV_ROOT_TOKEN_ID
          value: dev-token
        - name: VAULT_ADDR
          value: http://127.0.0.1:8200
        image: docker.io/library/vault:latest
        name: vault-dev-server
        ports:
        - containerPort: 8200
          hostPort: 8200
        resources: {}
        securityContext:
          capabilities:
            add:
            - CAP_IPC_LOCK
            drop:
            - CAP_MKNOD
            - CAP_AUDIT_WRITE
        volumeMounts:
        - mountPath: /vault/file
          name: vault-file-pvc
        - mountPath: /vault/logs
          name: vault-logs-pvc
          #  restartPolicy: Always
      volumes:
      - name: vault-file-pvc
        persistentVolumeClaim:
          claimName: local-path-pvc
      - name: vault-logs-pvc
        persistentVolumeClaim:
          claimName: local-path-pvc2