apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ca-secret
  namespace: cert-manager
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: ca-secret
  data:
  - secretKey: ca.crt
    remoteRef:
      key: cert/rootca
      property: base64