apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: vault-cluster-issuer
  annotations:
    avp.kubernetes.io/path: "secret/cert/rootca/"
    argocd.argoproj.io/sync-wave: "1"
spec:
  vault:
    server: https://vault.vault.svc.cluster.local:8200
    path: pki_int/sign/local-dot-lan
    caBundle: <base64>
    auth:
      kubernetes:
        mountPath: /v1/auth/kubernetes
        role: issuer
        secretRef:
          name: issuer-token-k3s-mgmt
          key: token
