apiVersion: v1
kind: Secret
metadata:
  name: issuer-token-k3s-mgmt
  namespace: cert-manager
  annotations:
    kubernetes.io/service-account.name: vault-issuer
type: kubernetes.io/service-account-token