apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: vault-cluster-issuer
spec:
  vault:
    server: https://vault.vault.svc.cluster.local:8200
    path: pki_int/sign/local-dot-lan
    caBundleSecretRef:
      key: server_ca.crt
      name: ca-secret
    auth:
      kubernetes:
        mountPath: /v1/auth/kubernetes
        role: vault-issuer-role
        serviceAccountRef:
          name: vault-issuer
