apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: vault-issuer
spec:
  vault:
    server: https://vault.vault.svc.cluster.local:8200
    path: pki_int/sign/local-dot-lan
    caBundle: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJkekNDQVIyZ0F3SUJBZ0lCQURBS0JnZ3Foa2pPUFFRREFqQWpNU0V3SHdZRFZRUUREQmhyTTNNdGMyVnkKZG1WeUxXTmhRREUzTkRFMU56RTFNREV3SGhjTk1qVXdNekV3TURFMU1UUXhXaGNOTXpVd016QTRNREUxTVRReApXakFqTVNFd0h3WURWUVFEREJock0zTXRjMlZ5ZG1WeUxXTmhRREUzTkRFMU56RTFNREV3V1RBVEJnY3Foa2pPClBRSUJCZ2dxaGtqT1BRTUJCd05DQUFTMmcyd3BhSStxNGhQZ25hYlJRVVNmZTl1KzhqbDZ5ck9Qa2lDUExWYWkKdHhRRSt4TEE4VkRXUERXMUMySy9hemMvRFhERk82dzhNZ1lKbW9FaklxL3ZvMEl3UURBT0JnTlZIUThCQWY4RQpCQU1DQXFRd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBZEJnTlZIUTRFRmdRVWJQUzcxcU5MOTRDSlF4SzFnMkc0Cjl0M0hwbEF3Q2dZSUtvWkl6ajBFQXdJRFNBQXdSUUloQUlHZTZBYndNYnZvK004RzkxZTZOV1RMTkl4aGczY2kKUWpHWnVnNDVidVl4QWlBSDlQdU8xdllQamhxdGdKOWlOQ1gyTEZQWnc2VXBJcWxudnp4L3RMSlJNdz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K"
    auth:
      kubernetes:
        mountPath: /v1/auth/kubernetes
        role: vault-issuer
        serviceAccountRef:
          name: vault-issuer
