apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: es-tsig-key
  namespace: external-dns
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: tsig-key
  data:
  - secretKey: rfc2136_tsig_secret
    remoteRef:
      key: technitium/tsig
      property: external-dns
