apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-rbac-cm
data:
  policy.default: role:readonly
  scopes: '[groups, email]'
  policy.csv: |
     p, role:org-admin, applications, *, */*, allow
     p, role:org-admin, clusters, get, *, allow
     p, role:org-admin, repositories, get, *, allow
     p, role:org-admin, repositories, create, *, allow
     p, role:org-admin, repositories, update, *, allow
     p, role:org-admin, repositories, delete, *, allow
     g, "9ba382d7-828d-45f1-b2b1-8da5ad23aeed", role:org-admin
     g, "9df50670-cdd7-410e-9d4d-1a87b389b4d6", role:org-admin
     g, "81610411-ae6f-47de-9636-2385b899e660", role:org-admin
     g, "edward.ingram@ycdisp.com", role:org-admin
