apiVersion: v1
stringData:
  admin.password: <ssh_password_bcrypt>
  admin.passwordMtime: "$(date +%FT%T%Z)"
kind: Secret
metadata:
  name: argocd-secret
  annotations:
    avp.kubernetes.io/path: "secret/ssh/ansible"
type: Opaque
