apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
- name: quay.io/argoproj/argocd
  newTag: v2.13.1

namespace: argocd

resources:
- argocd-install.yaml
- argocd-secret.yaml
# - argocd-repo-server-rbac.yaml
# - cmp-plugin.yaml
# - argocd-vault-plugin-credentials.yaml

configMapGenerator:
- name: argocd-cmd-params-cm
  behavior: merge
  literals:
  - server.insecure=true

patches:
# - path: argocd-repo-server.yaml
- path: argocd-rbac-cm.yaml
- path: argocd-cm.yaml
