apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: galaxy-clus1
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/eingram23/kubernetes.git
    targetRevision: main
    path: argocd/environments/prod/clus1/overlays/galaxy
  destination:
    namespace: galaxy
    server: https://rancher.local.lan/k8s/clusters/c-m-2bd2wzm5
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true