apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kafka-clus1
  namespace: argocd
spec:
  project: default
  sources:
  - repoURL: https://github.com/eingram23/kubernetes.git
    targetRevision: main
    path: argocd/environments/prod/clus1/overlays/kafka
  - repoURL: https://github.com/eingram23/kubernetes.git
    targetRevision: main
    path: argocd/environments/prod/clus1/manifests/kafka
  destination:
    namespace: kafka
    server: https://rancher.local.lan/k8s/clusters/c-m-99tbw7lr
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
      - CreateNamespace=true