apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: influxdb2
  namespace: argocd
spec:
  destination:
    namespace: influxdb2
    server: https://kubernetes.default.svc
  project: default
  sources:
    - repoURL: https://github.com/influxdata/helm-charts.git
      targetRevision: HEAD
      chart: influxdb2
      helm:
        valueFiles:
          - $values/argoapps/influxdb2/values-test.yaml
    - repoURL: https://github.com/eingram23/kubernetes.git
      targetRevision: HEAD
      ref: values
  syncPolicy:
    syncOptions:
      - CreateNamespace=true