apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: influxdb2
  namespace: argocd
spec:
  destination:
    namespace: influxdb2
    server: https://kubernetes.default.svc
  project: default
  sources:
    - repoURL: https://github.com/influxdata/helm-charts.git
      path: charts/influxdb2
      targetRevision: HEAD
    - repoURL: https://github.com/eingram23/kubernetes.git
      helm:
        valueFiles:
          - values-test.yaml
      path: argoapps/influxdb2
      targetRevision: HEAD
  syncPolicy:
    syncOptions:
      - CreateNamespace=true