apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: influxdb2
  namespace: argocd
spec:
  destination:
    namespace: influxdb2
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      valueFiles:
        - values-test.yaml
    path: argoapps/influxdb2
    repoURL: https://github.com/eingram23/kubernetes.git
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
      - CreateNamespace=true