apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: gitea-tls
  namespace: gitea
spec:
  secretName: gitea-tls
  issuerRef:
    kind: ClusterIssuer
    name: vault-issuer
  commonName: gitea-dev.local.lan
  dnsNames:
  - gitea-dev.local.lan
  duration: 8760h
  renewBefore: 4380h