{{- if .Values.ingressroute.enabled }}
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  entryPoints:
    {{- range .Values.ingressRoute.entryPoints }}
    - {{ . }}
    {{- end }}
  routes:
    - match: Host(`{{ .Values.ingressRoute.routes[0].match }}`)
      kind: Rule
      services:
        - name: {{ .Values.ingressRoute.routes[0].services[0].name }}
          port: {{ .Values.ingressRoute.routes[0].services[0].port }}
