---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: es-arc-runners-ghcr-secret
  namespace: arc-runners
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    type: kubernetes.io/dockerconfigjson
    name: arc-runners-ghcr-secret
    data:
      .dockerconfigjson: "{{ .dockerconfig | toString }}"
  data:
  - secretKey: dockerconfig
    remoteRef:
      key: github/pat
      property: dockerconfig
