---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: es-arc-runners-ghcr-secret
  namespace: arc-runners
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: arc-runners-ghcr-secret
  data:
  - secretKey: docker-username
    remoteRef:
      key: github/pat
      property: username
  - secretKey: docker-password
    remoteRef:
      key: github/pat
      property: homelab-packages-token
  - secretKey: docker-email
    remoteRef:
      key: github/pat
      property: email
  - secretKey: docker-server
    remoteRef:
      key: github/pat
      property: server

