apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: es-arc-runners-secret
  namespace: arc-runners
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: arc-runners-secret
  data:
  - secretKey: github_token
    remoteRef:
      key: github/pat
      property: gha-runner