apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
- name: quay.io/argoproj/argocd
  newTag: v2.13.1

namespace: argocd

resources:
- argocd-ingressroute.yaml
- cert.yaml
- argocd-repo-server-rbac.yaml
- cmp-plugin.yaml
- argocd-vault-plugin-credentials.yaml
- https://raw.githubusercontent.com/argoproj/argo-cd/v2.13.1/manifests/install.yaml

configMapGenerator:
- name: argocd-cmd-params-cm
  behavior: merge
  literals:
  - server.insecure=true

patches:
- path: argocd-secret.yaml
- path: argocd-repo-server.yaml
