apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: arc-runners-mgmt
  namespace: argocd
spec:
  project: default
  sources:
  - repoURL: ghcr.io/actions/actions-runner-controller-charts
    targetRevision: 0.10.1
    chart: gha-runner-scale-set
    helm:
      releaseName: arc-runners
      valueFiles:
      - $values/argocd/environments/dev/mgmt/values/arc-runners.yaml
  - repoURL: https://github.com/eingram23/kubernetes.git
    targetRevision: main
    ref: values
  - repoURL: https://github.com/eingram23/kubernetes.git
    targetRevision: main
    path: argocd/environments/dev/mgmt/manifests/arc-runners
  destination:
    namespace: arc-runners
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
