apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: arc
  namespace: argocd
spec:
  project: default
  sources:
  - repoURL: ghcr.io/actions/actions-runner-controller-charts
    targetRevision: 0.10.1
    chart: gha-runner-scale-set-controller
    helm:
      valueFiles:
      - $values/argocd/environments/dev/mgmt/values/arc.yaml
  - repoURL: https://github.com/eingram23/kubernetes.git
    targetRevision: main
    ref: values
  destination:
    namespace: arc-systems
    server: https://kubernetes.default.svc
  syncPolicy:
    # automated:
    #   prune: true
    #   selfHeal: true
    syncOptions:
    - CreateNamespace=true
