apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns-mgmt
  namespace: argocd
spec:
  project: default
  sources:
  - repoURL: https://github.com/eingram23/kubernetes.git
    targetRevision: main
    path: argocd/apps/external-dns
    helm:    
      releaseName: external-dns
      valueFiles:
      - $values/argocd/environments/dev/mgmt/values/external-dns.yaml
  - repoURL: https://github.com/eingram23/kubernetes.git
    targetRevision: main
    ref: values
  - repoURL: https://github.com/eingram23/kubernetes.git
    targetRevision: main
    path: argocd/environments/dev/mgmt/manifests/external-dns
  destination:
    namespace: external-dns
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
