apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kickstart-http-mgmt
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/eingram23/kubernetes.git
    targetRevision: main
    path: argocd/apps/kickstart-http
  destination:
    namespace: kickstart-http
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
