apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault-mgmt
  namespace: argocd
spec:
  project: default
  ignoreDifferences:
    - group: admissionregistration.k8s.io
      kind: MutatingWebhookConfiguration
      jqPathExpressions:
        - '.webhooks[]?.clientConfig.caBundle'
  sources:
  - repoURL: https://github.com/eingram23/kubernetes.git
    targetRevision: main
    path: argocd/apps/vault
    helm:
      releaseName: vault
      valueFiles:
      - $values/argocd/environments/dev/mgmt/values/vault.yaml
  - repoURL: https://github.com/eingram23/kubernetes.git
    targetRevision: main
    ref: values
  - repoURL: https://github.com/eingram23/kubernetes.git
    targetRevision: main
    path: argocd/environments/dev/mgmt/manifests/vault
  destination:
    namespace: vault
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
