apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns-clus1-dev
  namespace: argocd
spec:
  project: default
  sources:
  - repoURL: https://github.com/eingram23/kubernetes.git
    targetRevision: main
    path: argocd/apps/external-dns
    helm:    
      releaseName: external-dns
      valueFiles:
      - $values/argocd/environments/dev/clus1/values/external-dns.yaml
  - repoURL: https://github.com/eingram23/kubernetes.git
    targetRevision: main
    ref: values
  destination:
    namespace: external-dns
    server: https://rancher.local.lan/k8s/clusters/c-m-w4fjmt4t
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
    - CreateNamespace=true
