apiVersion: galaxy.ansible.com/v1beta1
kind: Galaxy
metadata:
  name: galaxy
spec:
  image: quay.io/ansible/galaxy-ng
  image_version: latest
  image_web: quay.io/ansible/galaxy-ui
  image_web_version: latest
  no_log: false
  admin_password_secret: "galaxy-admin-password"
  postgres_configuration_secret: "postgres-configuration-secret"
  # signing_secret: "signing-galaxy"
  # signing_scripts_configmap: "signing-scripts"
  hostname: galaxy.local.lan
  ingress_type: ingress
  ingress_class_name: nginx
  ingress_hosts:
    - hostname: galaxy.local.lan
      tls_secret: awx-tls
  ingress_annotations: |
    cert-manager.io/cluster-issuer: "vault-issuer"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
  nginx_client_max_body_size: 100m
  storage_type: File
  ingress_tls_secret: tls-galaxy-ingress
  file_storage_access_mode: ReadWriteMany
  file_storage_size: 20Gi
  # pulp_settings:
  #   allowed_export_paths:
  #     - /tmp
  #   allowed_import_paths:
  #     - /tmp
  #   telemetry: false
  content:
    replicas: 1
    resource_requirements:
      requests:
        cpu: 150m
        memory: 256Mi
      limits:
        cpu: 800m
        memory: 1Gi
  worker:
    replicas: 1
    resource_requirements:
      requests:
        cpu: 150m
        memory: 256Mi
      limits:
        cpu: 800m
        memory: 1Gi
  web:
    replicas: 1
    resource_requirements:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 800m
        memory: 1Gi