apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  project: default
  sources:
    - repoURL: https://github.com/eingram23/kubernetes.git
      targetRevision: main
      path: argocd/env/common/helm-apps/cert-manager
      helm:
        valueFiles:
          - values-prod.yaml
    - repoURL: https://github.com/eingram23/kubernetes.git
      targetRevision: main
      path: argocd/env/common/helm-apps/cert-manager/manifests
  destination:
    namespace: cert-manager
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true