apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
#   # Find the latest tag here: https://github.com/ansible/awx-operator/releases
  - github.com/ansible/awx-operator/config/default?ref=2.19.1
  - base/awx.yaml
  - base/awx-admin-password.yaml
  - base/awx-cert-vault.yaml
  - base/awx-ingressroute-vault.yaml
  - base/awx-secret-key.yaml
  - base/awx-cabundle.yaml

# # Set the image tags to match the git version from above
images:
  - name: quay.io/ansible/awx-operator
    newTag: 2.19.1

# Specify a custom namespace in which to install AWX
namespace: awx
