apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: es-awx-postgres-configuration-secret
  namespace: awx
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: postgres_configuration_secret
  stringData:
    host: <external ip or url resolvable by the cluster>
    port: <external port, this usually defaults to 5432>
    database: <desired database name>
    username: <username to connect as>
  - secretKey: password
    remoteRef:
      key: ssh/ansible
      property: ssh_password
    password: <password to connect with>
    sslmode: prefer
    target_session_attrs: read-write
    type: unmanaged