apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: core-app-of-apps
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/eingram23/kubernetes.git
    targetRevision: main
    path: argocd/environments/dev/dev1
  destination:
    namespace: argocd
    server: 'https://kubernetes.default.svc'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=false