apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: core-app-of-apps-rancher
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/eingram23/kubernetes.git
    targetRevision: main
    path: argocd/environments/dev/rancher
  destination:
    namespace: argocd
    server: 'https://k3s-rancher-cp1.local.lan:6443'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=false
