apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argocd-tls
  namespace: argocd
spec:
  secretName: argocd-tls
  issuerRef:
    kind: ClusterIssuer
    name: vault-cluster-issuer
  commonName: argocd-k3s-mgmt.local.lan
  dnsNames:
    - argocd-k3s-mgmt.local.lan
  duration: 8760h
  renewBefore: 4380h