apiVersion: v1
kind: ConfigMap
metadata:
  name: kickstart-config
  namespace: kickstart-http
  labels:
    app: kickstart-http
data:
  ks-rocky9-rke.cfg: |
    # version=RHEL9
    # Use text install
    text

    repo --name="AppStream" --baseurl=file:///run/install/sources/mount-0000-cdrom/AppStream

    %addon com_redhat_kdump --enable --reserve-mb='auto'

    %end

    %packages
    @^minimal-environment

    %end

    # Keyboard layouts
    keyboard --xlayouts='us'
    # System language
    lang en_US.UTF-8

    # Network information
    network  --bootproto=dhcp --device=ens192 --ipv6=auto --activate
    network  --hostname=rocky-temp.local

    # Use CDROM installation media
    cdrom

    # Run the Setup Agent on first boot
    firstboot --enable

    ignoredisk --only-use=sda
    # System bootloader configuration
    bootloader --append="crashkernel=auto" --location=mbr --boot-drive=sda
    # Partition clearing information
    clearpart --none --initlabel
    # Disk partitioning information
    part /boot --fstype="xfs" --ondisk=sda --size=1024
    part pv.213 --fstype="lvmpv" --ondisk=sda --size=59768
    part /boot/efi --fstype="efi" --ondisk=sda --size=600 --fsoptions="umask=0077,shortname=winnt"
    volgroup rl --pesize=4096 pv.213
    logvol /home --fstype="xfs" --size=20480 --name=home --vgname=rl
    logvol / --fstype="xfs" --size=47104 --name=root --vgname=rl
    logvol swap --fstype="swap" --size=2412 --name=swap --vgname=rl

    # System timezone
    timezone America/Los_Angeles --isUtc --ntpservers=2.pool.ntp.org,2.pool.ntp.org,2.pool.ntp.org,2.pool.ntp.org

    # Root password
    rootpw --allow-ssh temppassword

    # Reboot after installation
    reboot
  ks-rocky9.cfg: |
    #version=RHEL9
    # Use text install
    text

    %addon com_redhat_kdump --enable --reserve-mb='auto'

    %end

    %packages
    @^minimal-environment

    %end

    # Keyboard layouts
    keyboard --xlayouts='us'
    # System language
    lang en_US.UTF-8

    # Network information
    network  --bootproto=dhcp --device=ens192 --ipv6=auto --activate
    network  --hostname=rocky-temp.local

    # Use CDROM installation media
    cdrom
    repo --name="BaseOS" --baseurl=file:///run/install/repo/BaseOS
    repo --name="AppStream" --baseurl=file:///run/install/repo/AppStream

    # Run the Setup Agent on first boot
    firstboot --enable

    ignoredisk --only-use=sda
    # System bootloader configuration
    bootloader --append="crashkernel=auto" --location=mbr --boot-drive=sda
    # Partition clearing information
    clearpart --none --initlabel
    # Disk partitioning information
    part /boot --fstype="xfs" --ondisk=sda --size=1024
    part pv.213 --fstype="lvmpv" --ondisk=sda --size=59768
    part /boot/efi --fstype="efi" --ondisk=sda --size=600 --fsoptions="umask=0077,shortname=winnt"
    volgroup rl --pesize=4096 pv.213
    logvol /home --fstype="xfs" --size=20480 --name=home --vgname=rl
    logvol / --fstype="xfs" --size=47104 --name=root --vgname=rl
    logvol swap --fstype="swap" --size=2412 --name=swap --vgname=rl

    # System timezone
    timezone America/Los_Angeles --isUtc --ntpservers=2.pool.ntp.org,2.pool.ntp.org,2.pool.ntp.org,2.pool.ntp.org

    # Root password
    rootpw --allow-ssh temppassword

    # Reboot after installation
    reboot  

  ks-rocky10.cfg: |
    #version=RHEL10
    # Use text install
    text

    %addon com_redhat_kdump --enable --reserve-mb='auto'

    %end

    # Keyboard layouts
    keyboard --vckeymap=us --xlayouts='us'
    # System language
    lang en_US.UTF-8

    # Network information
    network  --bootproto=dhcp --device=ens192 --ipv6=auto --activate
    network  --hostname=rocky-temp.local

    # Use CDROM installation media
    cdrom
    # repo --name="AppStream" --baseurl=file:///run/install/repo/AppStream

    %packages
    @^minimal-environment

    %end

    # Run the Setup Agent on first boot
    firstboot --enable

    # Generated using Blivet version 3.10.0
    ignoredisk --only-use=sda
    # Partition clearing information
    clearpart --none --initlabel
    # Disk partitioning information
    part /boot/efi --fstype="efi" --ondisk=sda --size=600 --fsoptions="umask=0077,shortname=winnt"
    part /boot --fstype="xfs" --ondisk=sda --size=1024
    part pv.966 --fstype="lvmpv" --ondisk=sda --size=59814
    volgroup rl --pesize=4096 pv.966
    logvol swap --fstype="swap" --size=2088 --name=swap --vgname=rl
    logvol / --fstype="xfs" --grow --maxsize=71680 --size=1024 --name=root --vgname=rl
    logvol /home --fstype="xfs" --size=20480 --name=home --vgname=rl

    # System timezone
    timezone America/Los_Angeles --utc 
    timesource --ntp-server=2.pool.ntp.org,2.pool.ntp.org,2.pool.ntp.org,2.pool.ntp.org

    # Root password
    rootpw --allow-ssh temppassword

    # Reboot after installation
    reboot
  ubuntu26-cc: |
    #cloud-config
    autoinstall:
      version: 1
      apt:
        geoip: true
        preserve_sources_list: true
        primary:
          - arches: [amd64, i386]
            uri: http://us.archive.ubuntu.com/ubuntu
          - arches: [default]
            uri: http://ports.ubuntu.com/ubuntu-ports    
      early-commands:
        # Ensures that Packer does not connect too soon.
        - sudo systemctl stop ssh
      locale: en_US
      keyboard:
        layout: us
      storage:
        config:
          - type: disk
            id: disk-sda
            path: /dev/sda
            ptable: gpt
            wipe: superblock-recursive
            preserve: false
            grub_device: false
          - type: partition
            id: partition-0
            device: disk-sda
            number: 1
            size: 1127219200
            flag: boot
            wipe: superblock
            preserve: false
            grub_device: true
          - type: partition
            id: partition-1
            device: disk-sda
            number: 2
            size: 2147483648
            wipe: superblock
            preserve: false
            grub_device: false
          - type: partition
            id: partition-2
            device: disk-sda
            number: 3
            size: -1
            wipe: superblock
            preserve: false
            grub_device: false
          - type: format
            id: format-0
            volume: partition-0
            fstype: fat32
            preserve: false
          - type: format
            id: format-1
            volume: partition-1
            fstype: ext4
            preserve: false
          - type: lvm_volgroup
            id: lvm_volgroup-0
            name: ubuntu-vg
            devices: [partition-2]
            preserve: false
          - type: lvm_partition
            id: lvm_partition-0
            name: ubuntu-lv
            volgroup: lvm_volgroup-0
            size: -1
            wipe: superblock
            preserve: false
          - type: format
            id: format-2
            volume: lvm_partition-0
            fstype: ext4
            preserve: false
          - type: mount
            id: mount-2
            device: format-2
            path: /
          - type: mount
            id: mount-1
            device: format-1
            path: /boot
          - type: mount
            id: mount-0
            device: format-0
            path: /boot/efi
      identity:
        hostname: ubuntu-server
        username: tempuser
        password: $6$PtgsSOYcedPXOAbi$nbuIwp5OLrZ1opLUOKgfP8D0thOYCaCRHN6v6L38xWBRshvKWb7wor06rn6qwpu7yrK8VuQysUi8JMfT4DQLL.
      network:
        network:
          version: 2
          ethernets:
            ens33:
              dhcp4: true
              dhcp-identifier: mac
      ssh:
        install-server: true
        allow-pw: true
      packages:
        - openssh-server
        - open-vm-tools
        - net-tools
        - cloud-init
      user-data:
        disable_root: false
        package_update: true
        package_upgrade: true
        package_reboot_if_required: true
      timezone: UTC
      late-commands:
        - curtin in-target --target=/target -- sh -c 'printf "%s\n" "tempuser ALL=(ALL) NOPASSWD:ALL" > /etc/sudoers.d/90-tempuser'
        - curtin in-target --target=/target -- chmod 0440 /etc/sudoers.d/90-tempuser
        - curtin in-target --target=/target -- visudo -cf /etc/sudoers.d/90-tempuser
        - vmware-toolbox-cmd config set deployPkg enable-custom-scripts true
  metadata: |
    # empty placeholder
