apiVersion: v1
kind: ConfigMap
metadata:
  name: rocky9-kickstart-config
  namespace: kickstart-http
  labels:
    app: kickstart-http
    os: rocky9
data:
  kickstart.cfg: |
    #version=RHEL9
    # Use text mode install
    text
    
    # System language
    lang en_US.UTF-8
    
    # Keyboard layouts
    keyboard us
    
    # Network information
    network --bootproto=dhcp --device=link --activate
    
    # Use network installation
    url --url="http://download.rockylinux.org/pub/rocky/9/BaseOS/x86_64/os/"
    repo --name="AppStream" --baseurl="http://download.rockylinux.org/pub/rocky/9/AppStream/x86_64/os/"
    
    # Root password
    rootpw --plaintext changeme
    
    # System timezone
    timezone America/New_York --utc
    
    # System bootloader configuration
    bootloader --location=mbr
    
    # Partition clearing information
    clearpart --all --initlabel
    
    # Disk partitioning information
    autopart
    
    # System services
    services --enabled="chronyd"
    
    # Reboot after installation
    reboot
    
    %packages
    @core
    chrony
    %end
    
    %post
    # Post-installation script
    echo "Post-installation setup complete" > /root/post-install.log
    %end
