apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
- name: quay.io/argoproj/argocd
  newTag: v2.13.1

namespace: argocd

resources:
- base/ingressroute.yaml
- base/cert.yaml
- base/argocd-repo-server-rbac.yaml
- base/cmp-plugin.yaml
- base/argocd-vault-plugin-credentials.yaml
- https://raw.githubusercontent.com/argoproj/argo-cd/v2.13.1/manifests/install.yaml

configMapGenerator:
- name: argocd-cmd-params-cm
  behavior: merge
  literals:
  - server.insecure=true

patches:
- path: overlays/argocd-secret.yaml
- path: overlays/argocd-repo-server.yaml
