apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd
resources:
- base/ingressroute.yaml
- base/cert.yaml
- cmp-plugin.yaml
- argocd-vault-plugin-credentials.yaml
- https://raw.githubusercontent.com/argoproj/argo-cd/v2.13.1/manifests/install.yaml

patches:
- path: overlays/argocd-secret.yaml
- path: overlays/argocd-repo-server.yaml
