apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: es-awx-postgres-configuration-secret
  namespace: awx
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: awx-postgres-configuration
    template:
      type: Opaque
      engineVersion: v2
      data:
        host: homenas.local.lan
        port: 5433
        database: awx
        username: awx
        sslmode: prefer
        target_session_attrs: read-write
        type: unmanaged
  data:
  - secretKey: password
    remoteRef:
      key: ssh/ansible
      property: ssh_password

    