apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: awx

resources:
- github.com/ansible/awx-operator/config/default?ref=2.19.1
- https://github.com/eingram23/kubernetes.git/argocd/apps/awx?ref=main
- awx-postgres-configuration-secret.yaml
- awx.yaml