apiVersion: run.tanzu.vmware.com/v1alpha2
kind: TanzuKubernetesCluster
metadata:
  name: tkgs-test-cluster1
  namespace: homelab
spec:
  topology:
    controlPlane:
      replicas: 1
      vmClass: best-effort-xsmall
      storageClass: vsan-default-storage-policy
      tkr:  
        reference:
          name: v1.24.9---vmware.1-tkg.4
    nodePools:
    - name: worker-nodepool-a1
      replicas: 1
      vmClass: best-effort-xsmall
      storageClass: vsan-default-storage-policy
      tkr:  
        reference:
          name: v1.24.9---vmware.1-tkg.4
  settings:
    network:
      pods:
        cidrBlocks: ["192.0.5.0/16"]