apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: awx-operator
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ansible/awx-operator
    targetRevision: 2.19.1
    path: config/default
  destination:
    namespace: awx
    server: 'https://kubernetes.default.svc'
  syncPolicy:
    syncOptions:
      - CreateNamespace=true