apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: grafana-tls
  namespace: monitoring
spec:
  secretName: grafana-tls
  issuerRef:
    kind: ClusterIssuer
    name: vault-issuer
  commonName: grafana-k3s-mgmt.local.lan
  dnsNames:
  - grafana-k3s-mgmt.local.lan
  duration: 8760h
  renewBefore: 4380h