apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: prometheus-tls
  namespace: monitoring
spec:
  secretName: prometheus-tls
  issuerRef:
    kind: ClusterIssuer
    name: vault-issuer
  commonName: prometheus-k3s-mgmt.local.lan
  dnsNames:
  - prometheus-k3s-mgmt.local.lan
  duration: 8760h
  renewBefore: 4380h