apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: es-awx-admin-password
  namespace: awx
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: awx-admin-password
  data:
  - secretKey: password
    remoteRef:
      key: ssh/ansible
      property: ssh_password
