apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: es-awx-secret-key
  namespace: awx
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: awx-secret-key
  data:
  - secretKey: secret_key
    remoteRef:
      key: ssh/ansible
      property: ssh_password
