apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: es-azure-credentials
  namespace: vault
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: azure-credentials
  data:
  - secretKey: AZURE_TENANT_ID
    remoteRef:
      key: azure/tenant
      property: id
  - secretKey: AZURE_CLIENT_ID
    remoteRef:
      key: azure/app/vault
      property: id
  - secretKey: AZURE_CLIENT_SECRET
    remoteRef:
      key: azure/app/vault
      property: secret
