apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  destination:
    namespace: cert-manager
    server: https://kubernetes.default.svc
  project: default
  sources:
    - repoURL: https://charts.jetstack.io
      targetRevision: v1.16.2
      chart: cert-manager
      helm:
        valuesObject:
          installCRDs: true
      annotations:
        argocd.argoproj.io/sync-wave: "-2"  # Install cert-manager and CRDs first
    - repoURL: https://github.com/eingram23/kubernetes.git
      targetRevision: main
      path: argoapps/cert-manager/manifests
      annotations:
        argocd.argoproj.io/sync-wave: "-1"  # Apply custom manifests after CRDs are ready
  syncPolicy:
    syncOptions:
      - CreateNamespace=true