apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
spec:
  destination:
    namespace: cert-manager
    server: https://kubernetes.default.svc
  project: default
  sources:
    - repoURL: https://charts.jetstack.io
      targetRevision: v1.16.2
      chart: cert-manager
      helm:
        valuesObject:
          installCRDs: true
    - repoURL: https://github.com/eingram23/kubernetes.git
      targetRevision: main
      path: argoapps/cert-manager/manifests
  syncPolicy:
    syncOptions:
      - CreateNamespace=true