apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: influxdb2
  namespace: argocd
spec:
  destination:
    namespace: influxdb2
    server: https://kubernetes.default.svc
  project: default
  sources:
    - repoURL: https://helm.influxdata.com/
      targetRevision: 2.1.2
      chart: influxdb2
      helm:
        valueFiles:
          - $values/argoapps/influxdb2/values-prod.yaml
    - repoURL: https://github.com/eingram23/kubernetes.git
      targetRevision: main
      ref: values
  syncPolicy:
    syncOptions:
      - CreateNamespace=true