apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
spec:
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  project: default
  sources:
    - repoURL: https://prometheus-community.github.io/helm-charts
      targetRevision: 66.2.2
      chart: kube-prometheus-stack
      helm:
        valueFiles:
          - $values/argoapps/kube-prometheus-stack/values-test.yaml
    - repoURL: https://github.com/eingram23/kubernetes.git
      targetRevision: main
      ref: values
  syncPolicy:
    syncOptions:
      - CreateNamespace=true