apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  destination:
    namespace: cert-manager
    server: https://kubernetes.default.svc
  project: default
  sources:
    - repoURL: https://github.com/eingram23/kubernetes.git
      targetRevision: main
      path: argocd/apps/cert-manager
      helm:
        valueFiles:
          - values.yaml
    - repoURL: https://github.com/eingram23/kubernetes.git
      targetRevision: main
      path: argocd/apps/cert-manager/manifests
  syncPolicy:
    syncOptions:
      - CreateNamespace=true