apiVersion: apps/v1
kind: Deployment
metadata:
  name: galaxy-content
spec:
  template:
    spec:
      containers:
        - name: content
          livenessProbe:
            timeoutSeconds: 30
          readinessProbe:
            timeoutSeconds: 30