apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: es-galaxy-admin-password
  namespace: galaxy
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: galaxy-admin-password
  data:
  - secretKey: password
    remoteRef:
      key: ssh/ansible
      property: ssh_password
