apiVersion: galaxy.ansible.com/v1beta1
kind: Galaxy
metadata:
  name: galaxy
spec:
  image: quay.io/ansible/galaxy-ng
  image_version: latest
  image_web: quay.io/ansible/galaxy-ui
  image_web_version: latest
  no_log: false
  admin_password_secret: "galaxy-admin-password"
  postgres_configuration_secret: "postgres-configuration-secret"
  # signing_secret: ""
  # signing_scripts_configmap: ""
  hostname: galaxy.local.lan
  ingress_type: ingress
  nginx_client_max_body_size: 100m
  storage_type: File
  ingress_tls_secret: tls-galaxy-ingress
  file_storage_access_mode: ReadWriteOnce
  file_storage_size: 20Gi
  pulp_settings:
    GALAXY_FEATURE_FLAGS:
      execution_environments: True
    allowed_export_paths:
      - /tmp
    allowed_import_paths:
      - /tmp
    telemetry: false
  content:
    replicas: 1
    resource_requirements:
      requests:
        cpu: 150m
        memory: 256Mi
      limits:
        cpu: 250m
        memory: 500Mi
  worker:
    replicas: 1
    resource_requirements:
      requests:
        cpu: 150m
        memory: 256Mi
      limits:
        cpu: 250m
        memory: 500Mi
  web:
    replicas: 1
    resource_requirements:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 250m
        memory: 500Mi