apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: es-gitea-admin-secret
  namespace: gitea
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: gitea-admin-secret
    template:
      type: Opaque
      engineVersion: v2
      data:
        username: eingram
        password: "{{ .password }}"
  data:
  - secretKey: password
    remoteRef:
      key: ssh/ansible
      property: ssh_password