apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: es-gitea-postgres-secret
  namespace: gitea
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: gitea-postgres-secret
  data:
  - secretKey: password
    remoteRef:
      key: ssh/ansible
      property: ssh_password