apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  project: default
  source:
  - repoURL: https://github.com/eingram23/kubernetes.git
    targetRevision: main
    path: argoapps/argocd/kustomize
  destination:
    namespace: argocd
    server: 'https://kubernetes.default.svc'
  syncPolicy:
    syncOptions:
      - CreateNamespace=true