apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
spec:
  project: default
  source:
    - repoURL: https://github.com/eingram23/kubernetes.git
      targetRevision: main
      path: argoapps/argocd/kustomize
  destination:
    namespace: default
    server: 'https://kubernetes.default.svc'
  syncPolicy:
    syncOptions:
      - CreateNamespace=true