apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  namespace: argocd
spec:
  project: default
  sources:
  - repoURL: https://github.com/eingram23/kubernetes.git
    targetRevision: main
    path: argocd/apps/ingress-nginx
    helm:
      valueFiles:
      - $values/argocd/environments/dev/rancher/values/ingress-nginx.yaml
  - repoURL: https://github.com/eingram23/kubernetes.git
    targetRevision: main
    ref: values
  destination:
    namespace: ingress-nginx
    server: https://k3s-rancher-cp1.local.lan:6443
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
