apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rancher-rancher
  namespace: argocd
spec:
  project: default
  sources:
  - repoURL: https://github.com/eingram23/kubernetes.git
    targetRevision: main
    path: argocd/apps/rancher
    helm:
      releaseName: rancher
      parameters:
      - name: hostname
        value: rancher-k3s-rancher.local.lan
      valueFiles:
      - $values/argocd/environments/dev/rancher/values/rancher.yaml
  - repoURL: https://github.com/eingram23/kubernetes.git
    targetRevision: main
    ref: values
  # - repoURL: https://github.com/eingram23/kubernetes.git
  #   targetRevision: main
  #   path: argocd/environments/dev/rancher/manifests/rancher
  destination:
    namespace: rancher
    server: https://k3s-rancher-cp1.local.lan:6443
  syncPolicy:
    # automated:
    #   prune: true
    #   selfHeal: true
    syncOptions:
    - CreateNamespace=true
