apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rancher
  namespace: argocd
spec:
  project: default
  sources:
  - repoURL: https://github.com/eingram23/kubernetes.git
    targetRevision: main
    path: argocd/apps/rancher
    helm:
      parameters:
      - name: hostname
        value: rancher-k3s-mgmt.local.lan
      valueFiles:
      - $values/argocd/environments/dev/mgmt/values/rancher.yaml
  - repoURL: https://github.com/eingram23/kubernetes.git
    targetRevision: main
    ref: values
  # - repoURL: https://github.com/eingram23/kubernetes.git
  #   targetRevision: main
  #   path: argocd/environments/dev/mgmt/manifests/rancher
  destination:
    namespace: rancher
    server: https://kubernetes.default.svc
  syncPolicy:
    # automated:
    #   prune: true
    #   selfHeal: true
    syncOptions:
    - CreateNamespace=true
